/**
 * US city dataset — 4,600+ cities with pop >= 10,000.
 * Generated by scripts/build-city-list.cjs from Census + GeoNames data.
 * FIPS codes match Census Bureau / CDC PLACES / CMS Hospital Compare APIs.
 */

import citiesData from './us-cities.json';

export interface CityDef {
  name: string;
  slug: string;
  state: string;
  stateCode: string;
  stateFIPS: string;
  countyFIPS: string;
  countyName: string;
  population: number;
  lat: number;
  lng: number;
  tier: number;
}

export const CITIES: CityDef[] = citiesData as CityDef[];

// Lookup by slug — O(1) via Map
const slugMap = new Map(CITIES.map(c => [c.slug, c]));
export function getCityBySlug(slug: string): CityDef | undefined {
  return slugMap.get(slug);
}

// Group by state
export function getCitiesByState(stateCode: string): CityDef[] {
  return CITIES.filter(c => c.stateCode === stateCode);
}

// Unique states list
export interface StateDef {
  code: string;
  name: string;
  slug: string;
}

export const US_STATES: StateDef[] = [...new Map(
  CITIES.map(c => [c.stateCode, {
    code: c.stateCode,
    name: c.state,
    slug: c.state.toLowerCase().replace(/\s+/g, '-'),
  }])
).values()].sort((a, b) => a.name.localeCompare(b.name));

// State lookup by slug
const stateSlugMap = new Map(US_STATES.map(s => [s.slug, s]));
export function getStateBySlug(slug: string): StateDef | undefined {
  return stateSlugMap.get(slug);
}

// Nearby cities by haversine distance
export function getNearbyCities(lat: number, lng: number, limit = 5, excludeSlug?: string): CityDef[] {
  const toRad = (d: number) => d * Math.PI / 180;
  const R = 6371; // km

  return CITIES
    .filter(c => c.slug !== excludeSlug)
    .map(c => {
      const dLat = toRad(c.lat - lat);
      const dLng = toRad(c.lng - lng);
      const a = Math.sin(dLat / 2) ** 2 +
        Math.cos(toRad(lat)) * Math.cos(toRad(c.lat)) * Math.sin(dLng / 2) ** 2;
      const dist = R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
      return { city: c, dist };
    })
    .sort((a, b) => a.dist - b.dist)
    .slice(0, limit)
    .map(({ city }) => city);
}
